"""empty message

Revision ID: 0fc9fb91a07d
Revises: c639ec4f79a9
Create Date: 2020-07-22 16:06:54.817338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc9fb91a07d'
down_revision = 'c639ec4f79a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('gusto', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'gusto')
    # ### end Alembic commands ###
