"""empty message

Revision ID: 57b29f4c9269
Revises: de743c519dcf
Create Date: 2020-07-21 02:13:31.519659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b29f4c9269'
down_revision = 'de743c519dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('correo', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'correo')
    # ### end Alembic commands ###
