"""empty message

Revision ID: 5bb38bd8b55a
Revises: 06457a539656
Create Date: 2020-07-24 23:38:52.575248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb38bd8b55a'
down_revision = '06457a539656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('email', sa.String(), nullable=False))
    op.drop_column('usuario', 'correo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('correo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('usuario', 'email')
    # ### end Alembic commands ###
